# Generated by Django 4.2.13 on 2024-05-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='job_title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
